### ISSUE TITLE
SEO implementation

### ISSUE THREAD

**Issue by ighosh98** [BITS-Periodical-Society/freelunch#83]
We need to implement Search Engine Optimization for the website once we start hosting it.
Some useful frameworks:
https://django-seo.readthedocs.io/en/latest/introduction/tutorial.html
Kindly discuss SEO strategies and frameworks to be used in this thread before implementing it.

**Comment by ighosh98** [comment]
Resources for reading and frameworks:
https://django-seo.readthedocs.io/en/latest/introduction/tutorial.html
https://medium.com/@bedjango/4-seo-tips-to-position-your-website-using-django-96999d373222
https://www.vinta.com.br/blog/2015/basic-seo-django/

**Comment by Ak-shay** [comment]
- [ ] Title of every page should be descriptive and short.
Here are some best practices you should follow for creating titles on pages:
- Each page should have a unique title.
- If practical, try to include your Primary Keyword Phrase in every title of every page.
- Begin the title of your home page with your Primary Keyword Phrase, followed by your best Secondary Keyword Phrases.
- Use more specific variations to your Primary Keyword Phrase on your specific product, service, or content pages.
- If you must include your company name, put it at the end of the title.
- Use the best form, plural or singular, for your keywords based on what WordTracker says is searched on more often.
- Do not overdo it - do not repeat your keywords more than 2 to 3 times in the title.
- Make sure the `<title>` tag is the first element in the `<head>` section of your page - this makes it easier for Google to find the page.
- [ ] Keep the site tree as close as possible to homepage(root).
- [ ] File name should be descriptive, contains keywords and  separated by hyphens.
- [ ]  Don't put javascript code in html file. Call them from external file.
- [ ] Reduce the use of HTML frames. They are not search engine friendly.
- [ ] Javascript drop-downs prevents spiders from crawling beyond our homepage. If you use them, be sure to include text links at the bottom of the page.
- [ ] Use of meta tags in HTML for keywords, description, robots and adding details. Using keywords 3-7 times are advisable beyond that will be considered as spam.
- [ ] Keywords used should be place in page content.
Here is a list of places where you should try to use your main keywords.
-  Keywords in the <title> tag(s).
-  Keywords in the <meta name="description">.
-  Keywords in the <meta name="keyword">.
-  Keywords in `<h1>` or other headline tags.
-  Keywords in the `<a href="http://yourcompany.com">keywords</a>` link tags.
-  Keywords in the body copy.
-  Keywords in alt tags.
-  Keywords in `<!-- insert comments here-->` comments tags.
-  Keywords in the URL or website address.
- [ ] Pay attention to stemming for your keywords - particularly to what the root word is and what Google considers to be a match for that word, when optimising pages over time.
- [ ] Listed below are some of the important points to note about anchors:
- The Anchor Title plays a very important role and is seen by most of the search engines. The anchor title should have appropriate keywords. Anchor title helps the site visitors using a balloon, and displaying written text.
- The Anchor Text is another important part, which should be selected very carefully because this text is used not only for search engines but also for navigation purpose. You should try to use the best keywords in your anchor text.
- The `otherpage.html` is the link to another webpage. This link could be to an external site. Here, you need to ensure that the linked page does exist; otherwise it is called a broken link, which gives a bad impression to search engines as well as to site visitors.
- example of an anchor could be as follows:
`<a href="otherpage.htm" title="Anchor Title">
   <img src="image.gif" alt="keywords" />
</a>`
- In this case, Anchor Text has been replaced by an image. So, while using an image in place of an anchor text, it should be checked that you have put alt tag properly. An image alt tag should have appropriate keywords.

**Comment by ighosh98** [comment]
Please check how many points we have violated so far in our design.
